package com.neuedu.dao;

import com.neuedu.pojo.UserInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    UserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    List<UserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserInfo record);

    /**
     *登录：用来校验username
     */
    int checkUsername(String username);

    /**
     *登录：用来校验邮箱
     */
    int checkEmail(String email);

    /**
     * 登录：利用用户名和密码查询信息
     */
    UserInfo selectUserByUsernameAndPassword(@Param("username") String username,@Param("password") String password);

    /**
     * 忘记密码：通过username查询密保问题
     */
    String getQuestionByUsername(String username);

    /**
     * 通过username,question,answer查询
     */
    int selectByUsernameAndQuestionAndAnswer(@Param("username") String username,@Param("question") String question,@Param("answer") String answer);

    /**
     * 修改用户密码
     */
    int updateUserPassword(@Param("username") String username,@Param("passwordNew") String passwordNew);

}